### PR TITLE
answered README ?s

### PR DESCRIPTION
**Pull request by fncischen**
@ryanboris

### CODE REVIEW

**Review by secantsquared — APPROVED** [review]
https://github.com/fncischen/Sprint-Challenge-Applied-Javascript/blob/4e0a5c5c0b57981f8f7820e3289a2afdfce0db93/components/Carousel/Carousel.js#L1-L69

I love your logic and implementation here.

**Review by secantsquared — APPROVED** [review]
Clear and correct implementation of the provided commentary.

**Review by secantsquared — APPROVED** [review]
Such a well done animation - awesome stuff @fncischen

**Comment by secantsquared** [comment]
MVP and Stretch confirmed
Another excellent week 
🥇

**Comment by fncischen** [comment]
Thanks @ryanboris !

**Pull request merged**
